name: Deploy to OpenShift

on:
  push:
    branches:
      - main
    paths:
      - 'htmlcode/**'
      - 'phpcode/**'
      - 'pythoncode/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install oc CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} \
            --token=${{ secrets.OPENSHIFT_TOKEN }} \
            --insecure-skip-tls-verify=true

      - name: Switch Project
        run: oc project ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Trigger Build
        run: oc start-build hello-world

      - name: Rollout Restart Deployment
<<<<<<< HEAD
        run: oc rollout restart deployment hello-world
=======
        run: oc rollout restart deployment hello-world
>>>>>>> 44d50b6d91d303df4c0ba69b5897b3c2571cd783
